---
title: "R Notebook"
output: html_notebook
---

```{r}
library(malecns)
library(dplyr)
```



```{r}
mcnsann.url="https://docs.google.com/spreadsheets/d/13e2yboGmSHrkdew0REkqXWrx5PfHrwPbZZArySjIHtA/edit#gid=0"
mcnsann=googlesheets4::read_sheet(mcnsann.url)
```

```{r}
mcns_xyz2bodyid(cbind(35802, 10687, 27016), node = 'neutu')
b1=mcns_xyz2bodyid(mcnsann$position, node = 'clio')
b2=mcns_xyz2bodyid(mcnsann$position, node = 'neuprint')
table(b1==b2)
```

```{r}
table(mcns_xyz2bodyid(mcnsann$position, node = 'clio')==mcnsann$bodyid)
table(mcns_xyz2bodyid(mcnsann$position, node = 'neuprint')==mcnsann$bodyid)
```

```{r}
mcnsann$bodyid=mcns_xyz2bodyid(mcnsann$position, node = 'neuprint')
```


```{r}
cnsc <- mcns_neuprint()
```


```{r}
da1.axons=subset(mcnsann, grepl("DA1",symbol) & grepl("axon", notes))
da1ds=neuprintr::neuprint_connection_table(da1.axons,partners = 'out', conn = cnsc)

unique(da1ds$bodyid)
```

```{r}
table(da1ds$bodyid)
```



```{r}
da1ds %>% 
  group_by(partner) %>% 
  summarise(weight=sum(weight), n=n()) %>% 
  arrange(desc(weight))

```

Or use the new summary arg

```{r}
da1dss=mcns_connection_table(da1.axons,partners = 'out', summary = T)
da1dss
```

```{r, eval=FALSE}
mcns_scene(da1dss$partner[1:10], open=T, node='neuprint')
mcns_scene(da1dss$partner[11:20], open=T, node='neuprint')
```


```{r}
da1dss %>% 
  filter(weight>=20) %>% 
  googlesheets4::write_sheet(., ss = mcnsann.url, sheet = 'DA1DS')
```


## Downstream of other neurons

mAL
```{r}
malds=mcns_connection_table(subset(mcnsann, symbol=='mAL'), partners = 'out', summary = T, threshold=10)
```

```{r, eval=F}
mcns_scene(malds$partner[1:10], open = T, node = 'neuprint')
malds %>% 
  filter(weight>=20) %>% 
  googlesheets4::write_sheet(., ss = mcnsann.url, sheet = 'mALDS')
```

lvPNs

```{r}
lvpnds=mcns_connection_table(subset(mcnsann, grepl('lvPN', symbol)), partners = 'out', summary = T, threshold=10)

```


```{r, eval=F}
mcns_scene(lvpnds$partner[1:10], open = T, node = 'neuprint')
lvpnds %>% 
  filter(weight>=20) %>% 
  googlesheets4::write_sheet(., ss = mcnsann.url, sheet = 'lvPNDS')

```

Downstream of DA1 PNs and lvPNs

```{r}
nrow(lvpnds)
```


comparing "half" and whole brain

half brain [xyz](https://tinyurl.com/2rjebtkv): 34184, 22285, 22479
whole brain [xyz](https://tinyurl.com/yeymbmuk): 38280, 26380, 26575 

```{r}
hb=cbind(34184, 22285, 22479)
wb=cbind(38280, 26380, 26575)
wb-hb
hb+4096
```

## Upstream of DA1 axons

```{r}
da1.in=mcns_connection_table(da1.axons$bodyid, partners = 'in', summary = T)
```

VA1v downstream

```{r}

```


## upstream of aSP-g

```{r}
aspgs=subset(mcnsann, symbol=='aSP-g')
aspgs.in=mcns_connection_table(aspgs$bodyid, partners = 'in', summary = T)

```


```{r}
left_join(aspgs.in, mcnsann, by=c("partner"="bodyid"))
```

