#' Surface models of the malecns brain (in nm)
#'
#' @description \code{malecns_shell.surf} is a surface model of the cortex
#'   (rind) of the malecns brain (in nm). It was downloaded from a link provided
#'   by Stuart Berg (of FlyEM).
#' @rdname malecns.surf
#' @docType data
#' @examples
#' \donttest{
#' library(nat)
#' boundingbox(malecns_shell.surf)
#' }
#' \dontrun{
#' plot3d(malecns_shell.surf, alpha=.2, col='grey')
#' # in microns
#' plot3d(malecns_shell.surf/1e3, alpha=.2, col='grey')
#' # in raw voxels
#' plot3d(malecns_shell.surf*(8/1e3), alpha=.2, col='grey')
#' # mesh3d gives more flexibility
#' plot3d(as.mesh3d(malecns_shell.surf), alpha=.2, col='grey', type='wire', add=T)
#' }
"malecns_shell.surf"


#' @description \code{malecns.surf} is a surface model of the malecns neuropil
#'   generated by Philipp Schlegel in May 2022 based on the location of T bars
#'   in the dataset. See
#'   \href{https://flyconnectome.slack.com/archives/C02F6UCCU6B/p1652961842009749?thread_ts=1652423869.552919&cid=C02F6UCCU6B}{slack}
#'   for details.
#'
#' @docType data
#' @rdname malecns.surf
#' @examples
#' \donttest{
#' library(nat)
#' boundingbox(malecns.surf)
#' }
#' \dontrun{
#' plot3d(malecns.surf, alpha=.2, col='grey')
#' # in microns
#' plot3d(malecns.surf/1e3, alpha=.2, col='grey')
#' # in raw voxels
#' plot3d(malecns.surf*(8/1e3), alpha=.2, col='grey')
#' # mesh3d gives more flexibility
#' plot3d(as.mesh3d(malecns.surf), alpha=.2, col='grey', type='wire', add=T)
#' }
"malecns.surf"


#' @docType data
#' @description \code{JRCFIB2022M.surf} and \code{malecns.surf} are aliases
#' @rdname malecns.surf
"JRCFIB2022M.surf"


#' @description \code{malecnsvnc_shell.surf} is a surface model of the cortex
#'   (rind) of the malecns ventral nerve cord (in nm). It was downloaded from a
#'   link provided by Stuart Berg (of FlyEM) on 2023-11-18.
#' @rdname malecns.surf
#' @docType data
#' @examples
#' \donttest{
#' library(nat)
#' boundingbox(malecnsvnc_shell.surf)
#' }
#' \dontrun{
#' nclear3d()
#' plot3d(malecns.surf, col='blue')
#' wire3d(malecns_shell.surf, col='grey')
#' plot3d(malecnsvnc.surf, col='blue')
#' wire3d(malecnsvnc_shell.surf, alpha=.2, col='green')
#' }
"malecnsvnc_shell.surf"


#' @description \code{malecnsvnc.surf} is a surface model of the neuropil
#'   of the malecns ventral nerve cord (in nm). It was downloaded from a
#'   link provided by Stuart Berg (of FlyEM) on 2025-05-09.
#' @rdname malecns.surf
#' @docType data
#' @examples
#' \donttest{
#' library(nat)
#' boundingbox(malecnsvnc.surf)
#' }
"malecnsvnc.surf"
